### ISSUE TITLE
Не верная версия Java

### ISSUE THREAD

**Issue by andreigerasimov** [MicrosoftDocs/azure-docs.ru-ru#174]
apt install default-jre -y
Не прокатит, используйте:
sudo add-apt-repository ppa:webupd8team/java
sudo apt-get install oracle-java8-installer

---
#### Сведения о документе

⚠ *Не вносите правки в этот раздел. Это необходимо для связывания страницы сайта docs.microsoft.com с вопросом на GitHub.*

* ID: a230cf42-66c2-e0d1-983a-7b920251fe2c
* Version Independent ID: 6d17ff45-c7fd-2715-382e-14905760b594
* Content: [Руководство. Создание конвейера разработки в Azure с помощью Jenkins](https://docs.microsoft.com/ru-ru/azure/virtual-machines/linux/tutorial-jenkins-github-docker-cicd)
* Content Source: [articles/virtual-machines/linux/tutorial-jenkins-github-docker-cicd.md](https://github.com/MicrosoftDocs/azure-docs.ru-ru/blob/live/articles/virtual-machines/linux/tutorial-jenkins-github-docker-cicd.md)
* Service: **virtual-machines-linux**
* GitHub Login: @zr-msft
* Microsoft Alias: **zarhoads**

**Comment by LisandroSu** [comment]
Issue moved to [MicrosoftDocs/azure-docs #24288](https://github.com/MicrosoftDocs/azure-docs/issues/24288) via [**ZenHub**](https://www.zenhub.com/)

**Comment by LisandroSu** [comment]
Здравствуйте, @<имя участника на GITHUB>! 

Благодарим Вас за участие. Ваш отзыв связан с исходной документацией. 
Поэтому мы переносим Вашу заявку в репозиторий по английскому языку. Ее состояние можно просмотреть здесь: https://github.com/MicrosoftDocs/azure-docs/issues/24288. 

Мы очень ценим Ваш вклад в наши статьи.  
С наилучшими пожеланиями, 
Международная команда поддержки документации Майкрософт

**Comment by LisandroSu** [comment]
Здравствуйте, @andreigerasimov 

Благодарим Вас за участие. Ваш отзыв связан с исходной документацией.
Поэтому мы переносим Вашу заявку в репозиторий по английскому языку. Ее состояние можно просмотреть здесь: [MicrosoftDocs/azure-docs#24288](https://github.com/MicrosoftDocs/azure-docs/issues/24288).

Мы очень ценим Ваш вклад в наши статьи.
С наилучшими пожеланиями,
Международная команда поддержки документации Майкрософт
