### ISSUE TITLE
 Integrations & services 

### ISSUE THREAD

**Issue by andreigerasimov** [MicrosoftDocs/azure-docs.ru-ru#175]
Integrations & services (Интеграция и службы) больше не поддерживается в github, используйте закладку webhook

---
#### Сведения о документе

⚠ *Не вносите правки в этот раздел. Это необходимо для связывания страницы сайта docs.microsoft.com с вопросом на GitHub.*

* ID: a230cf42-66c2-e0d1-983a-7b920251fe2c
* Version Independent ID: 6d17ff45-c7fd-2715-382e-14905760b594
* Content: [Руководство. Создание конвейера разработки в Azure с помощью Jenkins](https://docs.microsoft.com/ru-ru/azure/virtual-machines/linux/tutorial-jenkins-github-docker-cicd)
* Content Source: [articles/virtual-machines/linux/tutorial-jenkins-github-docker-cicd.md](https://github.com/MicrosoftDocs/azure-docs.ru-ru/blob/live/articles/virtual-machines/linux/tutorial-jenkins-github-docker-cicd.md)
* Service: **virtual-machines-linux**
* GitHub Login: @zr-msft
* Microsoft Alias: **zarhoads**

**Comment by LisandroSu** [comment]
Issue moved to [MicrosoftDocs/azure-docs #24295](https://github.com/MicrosoftDocs/azure-docs/issues/24295) via [**ZenHub**](https://www.zenhub.com/)

**Comment by LisandroSu** [comment]
Здравствуйте, @andreigerasimov ! 

Благодарим Вас за участие. Ваш отзыв связан с исходной документацией. 

Поэтому мы переносим Вашу заявку в репозиторий по английскому языку. Ее состояние можно просмотреть здесь: https://github.com/MicrosoftDocs/azure-docs/issues/24295. 

Мы очень ценим Ваш вклад в наши статьи.  

С наилучшими пожеланиями, 
Международная команда поддержки документации Майкрософт
