### ISSUE TITLE
Not working as desied

### ISSUE THREAD

**Issue by w55** [MicrosoftDocs/azure-docs.ru-ru#197]
Все делал как описано выше. Несколько раз перезагружал комп. Менял порты, настройки, сертификаты. В результате - так нечего и не заработало. Очень жаль.

---
#### Сведения о документе

⚠ *Не вносите правки в этот раздел. Это необходимо для связывания страницы сайта docs.microsoft.com с вопросом на GitHub.*

* ID: 3ac102a5-e9ad-0046-f217-446f1ad263c5
* Version Independent ID: a47523e2-0c30-dee4-0037-5f58836fa37f
* Content: [Добавление конечной точки HTTPS в приложение Service Fabric в Azure с использованием Kestrel](https://docs.microsoft.com/ru-ru/azure/service-fabric/service-fabric-tutorial-dotnet-app-enable-https-endpoint#feedback)
* Content Source: [articles/service-fabric/service-fabric-tutorial-dotnet-app-enable-https-endpoint.md](https://github.com/MicrosoftDocs/azure-docs.ru-ru/blob/live/articles/service-fabric/service-fabric-tutorial-dotnet-app-enable-https-endpoint.md)
* Service: **service-fabric**
* GitHub Login: @aljo-microsoft
* Microsoft Alias: **aljo**

**Comment by CeciAc** [comment]
Здравствуйте, @w55
Благодарим Вас за участие. Наши специалисты могут отвечать только на отзывы по документации. 
Чтобы оставить отзыв по продукту, воспользуйтесь кнопкой «Оставить отзыв о продукте» внизу страницы портала документации. 
А по текущему каналу Вы можете оставлять любые отзывы, связанные с документацией. 
Мы очень ценим Ваш вклад в наши статьи.  
С наилучшими пожеланиями, 
Международная команда поддержки документации Майкрософт
