### ISSUE TITLE
Publish symbols - type of symbols

### ISSUE THREAD

**Issue by yahorsi** [MicrosoftDocs/azure-docs.ru-ru#403]
Publish symbols section should include what type of symbols supported/should be used to make snapshot debugger woek correctly. Today there are several options available when building with symbols support, like pdb-only, portable, embeeded, full...

---
#### Сведения о документе

⚠ *Не вносите правки в этот раздел. Это необходимо для связывания страницы сайта docs.microsoft.com с вопросом на GitHub.*

* ID: ce8f1b18-83c6-0872-197a-c6320537578b
* Version Independent ID: 00173c2b-6efb-6749-3e8b-494e55d13006
* Content: [Отладчик моментальных снимков Azure Application Insights для приложений .NET](https://docs.microsoft.com/ru-ru/azure/azure-monitor/app/snapshot-debugger#publish-symbols)
* Content Source: [articles/azure-monitor/app/snapshot-debugger.md](https://github.com/MicrosoftDocs/azure-docs.ru-ru/blob/master/articles/azure-monitor/app/snapshot-debugger.md)
* Service: **application-insights**
* GitHub Login: @mrbullwinkle
* Microsoft Alias: **mbullwin**

**Comment by srvbpigh** [comment]
Hello, @yahorsi
 
Thank you for your feedback.
 
We are actively reviewing your comments and will get back to you soon.


Kind regards,
Microsoft DOCS International Team

**Comment by CeciAc** [comment]
Issue moved to [MicrosoftDocs/azure-docs #35779](https://github.com/MicrosoftDocs/azure-docs/issues/35779) via [**ZenHub**](https://www.zenhub.com/)

**Comment by CeciAc** [comment]
Hello, @yahorsi

Your contribution is much appreciated. Your feedback is related to the original documentation.
Hence, we are migrating this issue to the English repo. Please review the status of the issue here - https://github.com/MicrosoftDocs/azure-docs/issues/35779

We truly appreciate your contribution to our articles. 

Kind regards,
Microsoft DOCS International Team
