### ISSUE TITLE
Automatic Redirect to the localized page

### ISSUE THREAD

**Issue by yahorsi** [MicrosoftDocs/azure-docs.ru-ru#404]
Hi Guys,

2 issues in one :) Please split if needed.

1. I'd like to read all docs on English, but, If I open article on English docs site redirects me to the localized ru-ru version. I even turned on "read on english" but it still redirects me and I didn't find the way to stop it.

2. Docs issues I create are actually created in the wrong Github repo. Like, If I read doc on english issues are created on the russian docs repo... Even if I turned "read on english" on...

---
#### Сведения о документе

⚠ *Не вносите правки в этот раздел. Это необходимо для связывания страницы сайта docs.microsoft.com с вопросом на GitHub.*

* ID: d924ee5e-1bf1-0d35-24e2-5b222e8e44c5
* Version Independent ID: f33fdb83-7734-b0b0-0ebd-25c0a5383c32
* Content: [Справочник по файлу ApplicationInsights.config в Azure](https://docs.microsoft.com/ru-ru/azure/azure-monitor/app/configuration-with-applicationinsights-config#feedback)
* Content Source: [articles/azure-monitor/app/configuration-with-applicationinsights-config.md](https://github.com/MicrosoftDocs/azure-docs.ru-ru/blob/master/articles/azure-monitor/app/configuration-with-applicationinsights-config.md)
* Service: **application-insights**
* GitHub Login: @mrbullwinkle
* Microsoft Alias: **mbullwin**

**Comment by srvbpigh** [comment]
Hello, @yahorsi
 
Thank you for your feedback.
 
We are actively reviewing your comments and will get back to you soon.


Kind regards,
Microsoft DOCS International Team

**Comment by CeciAc** [comment]
Hi @ishasahni1 
Can you please check this issue?

**Comment by ishasahni1** [comment]
@bodhigautam can you please help us looking into this Issue.

@CeciAc FYI

**Comment by bodhigautam** [comment]
For 1. You can select your language from the language picker. Just scroll down to the bottom of the page, click on the language picker on bottom left and select your preferred language as English(United States). This will ensure that your language preference are taken into consideration whenever you open a page on docs.
For 2. Enabling Read in English toggle will still keep the main repo as Russian as you are seeing the Russian Page. Hence the GitHub issue gets open in Russian repo. To open the github issues on English you would have to first select the language as English from the Language picker. cc @CeciAc @ishasahni1

**Comment by ishasahni1** [comment]
@yahorsi can you kindly let us know if the suggestion shared by Bodhi helps you address this issue.

**Comment by yahorsi** [comment]
> @yahorsi can you kindly let us know if the suggestion shared by Bodhi helps you address this issue.

Hi, thank you for reply. I would maybe suggest to make several usability improvements.
I suggest to consider following - 
1. Please, make is easier to switch languages, may be switch to the English as separate link/button/option. That option should have same visibility level as "read on english"
2. If user turns on - read on English, may be it make sense to redirect him to the original english page? Or at least suggest

The rest is fine, thank you
