### ISSUE TITLE
Страница бесполезна для Android пользователя

### ISSUE THREAD

**Issue by voroshilovalexy** [MicrosoftDocs/azure-docs.ru-ru#408]
Нп эту страницу перешёл со страницы "Резервное копирование и восстановление учетных данных с помощью приложения Microsoft Authenticator", полагая что речь пойдет о всех ОС для которых доступно приложение. Но тут подробная инструкция только для iOSj

---
#### Сведения о документе

⚠ *Не вносите правки в этот раздел. Это необходимо для связывания страницы сайта docs.microsoft.com с вопросом на GitHub.*

* ID: 8b52a210-1be6-4e5f-d95c-8ea7b87919ca
* Version Independent ID: 02a43ebb-7471-d7ff-4f7e-84c9f7a66326
* Content: [Резервное копирование и восстановление с помощью приложения Microsoft Authenticator: Azure Active Directory](https://docs.microsoft.com/ru-ru/azure/active-directory/user-help/user-help-auth-app-backup-recovery#feedback)
* Content Source: [articles/active-directory/user-help/user-help-auth-app-backup-recovery.md](https://github.com/MicrosoftDocs/azure-docs.ru-ru/blob/master/articles/active-directory/user-help/user-help-auth-app-backup-recovery.md)
* Service: **active-directory**
* Sub-service: **user-help**
* GitHub Login: @eross-msft
* Microsoft Alias: **lizross**

**Comment by srvbpigh** [comment]
Hello, @voroshilovalexy
 
Thank you for your feedback.
 
We are actively reviewing your comments and will get back to you soon.


Kind regards,
Microsoft DOCS International Team

**Comment by CeciAc** [comment]
Здравствуйте, @voroshilovalexy
Благодарим Вас за предоставленный комментарий. Комментарии помогают нам постоянно улучшать портал docs.microsoft.com. Однако нам необходимы дополнительные сведения, чтобы проанализировать Ваш отзыв. Не могли бы Вы дать более подробную информацию и пояснить свой комментарий?
С уважением,
Международная команда Microsoft DOCS

**Comment by CeciAc** [comment]
Здравствуйте, @voroshilovalexy
Обращаемся к Вам по поводу предыдущего комментария. Нам необходимы дополнительные сведения, чтобы проанализировать Ваш отзыв. Не могли бы Вы дать более подробную информацию и пояснить свой комментарий?
С уважением,
Международная команда Microsoft DOCS

**Comment by CeciAc** [comment]
Здравствуйте, @voroshilovalexy
Еще раз благодарим Вас за предоставленный комментарий.
К сожалению, у нас по-прежнему недостаточно данных для обработки Вашего отзыва. Пока что мы закрываем этот вопрос на GitHub, но надеемся получать от Вас подробные отзывы в будущем.
С уважением,
Международная команда Microsoft DOCS
