### ISSUE TITLE
Method names are incorrectly transliterated

### ISSUE THREAD

**Issue by izhovkin** [MicrosoftDocs/azure-docs.ru-ru#532]
Method names must not be transliterated:

жетпермиссионсасинк -> GetPermissionAsync
блобконтаинерпермиссионс -> BlobContainerPermissions

---
#### Сведения о документе

⚠ *Не вносите правки в этот раздел. Это необходимо для связывания страницы сайта docs.microsoft.com с вопросом на GitHub.*

* ID: a299cd29-143b-c263-7996-3467035b8937
* Version Independent ID: a8a1d0d0-411e-44eb-51da-c1f8ab90befa
* Content: [Включение открытого доступа на чтение к контейнерам и большим двоичным объектам в хранилище BLOB-объектов Azure](https://docs.microsoft.com/ru-ru/azure/storage/blobs/storage-manage-access-to-resources#feedback)
* Content Source: [articles/storage/blobs/storage-manage-access-to-resources.md](https://github.com/MicrosoftDocs/azure-docs.ru-ru/blob/master/articles/storage/blobs/storage-manage-access-to-resources.md)
* Service: **storage**
* GitHub Login: @tamram
* Microsoft Alias: **tamram**

**Comment by srvbpigh** [comment]
Hello, @izhovkin
 
Thank you for your feedback.
 
We are actively reviewing your comments and will get back to you soon.


Kind regards,
Microsoft DOCS International Team

**Comment by CeciAc** [comment]
Hello, @izhovkin 
 
Thank you for your feedback.
 
Our linguistic team reviewed your linguist suggestions and accepted them. We implemented your feedback and published to the updated articles on the Docs site to the following pages https://docs.microsoft.com/ru-ru/azure/storage/blobs/storage-manage-access-to-resources#feedback

We truly appreciate your contribution to our articles and we encourage you to continue providing your valuable feedback.
	
Kind regards,
Microsoft DOCS International Team
