### ISSUE TITLE
Ошибка в формате Url для хранилища ключей.

### ISSUE THREAD

**Issue by zsimvol** [MicrosoftDocs/azure-docs.ru-ru#585]
В строке:
Для этого вам нужен URL-адрес хранилища ключей в формате https://&lt;your-unique-keyvault-name&gt;.vault.azure.net/secrets/

Допущена ошибка т.к. формат должен быть следующий: https://&lt;your-unique-keyvault-name&gt;.vault.azure.net/
Формат Url'а из статьи приведет к ошибке: Operation cancelled with BadRequest

---
#### Сведения о документе

⚠ *Не вносите правки в этот раздел. Это необходимо для связывания страницы сайта docs.microsoft.com с вопросом на GitHub.*

* ID: bc43d849-5b06-7185-0c9e-aaf240363aca
* Version Independent ID: 385f4dfe-326a-9e63-80ce-3c71903edf3c
* Content: [Краткое руководство по использованию клиентской библиотеки Azure Key Vault для .NET](https://docs.microsoft.com/ru-ru/azure/key-vault/quick-create-net#feedback)
* Content Source: [articles/key-vault/quick-create-net.md](https://github.com/MicrosoftDocs/azure-docs.ru-ru/blob/master/articles/key-vault/quick-create-net.md)
* Service: **key-vault**
* GitHub Login: @msmbaldwin
* Microsoft Alias: **mbaldwin**

**Comment by srvbpigh** [comment]
Hello, @zsimvol
 
Thank you for your feedback.
 
We are actively reviewing your comments and will get back to you soon.


Kind regards,
Microsoft DOCS International Team

**Comment by CeciAc** [comment]
Здравствуйте, @zsimvol 

Благодарим за Ваш отзыв и предложение.  

Данный файл сейчас находится на этапе локализации. Эта статья будет опубликована в ближайшее время.

Большое спасибо за поддержку! 

С наилучшими пожеланиями,
Microsoft DOCS Global Experience Team
