### ISSUE TITLE
What could be the cause of the error “Unable to edit or replace deployment” ?

### ISSUE THREAD

**Issue by ksereda** [MicrosoftDocs/azure-docs.ru-ru#588]
Hi.
When I recreate my VM I got the following error:

Problem occurred during request to Azure services. Cloud provider details: Unable to edit or replace deployment 'VM-Name': previous deployment from '8/20/2019 6:20:33 AM' is still active (expiration time is '8/27/2019 5:17:41 AM'). Please see https://aka.ms/arm-deploy for usage details.

Help me please to understand. What could be the cause of the error ?

This deployment has not been started previously. Prior to this, errors were received during creation:

Azure is not available now. Please Try again later

There were several such errors one at a time and then I got that error related to:

Unable to edit or replace deployment

My assumptions about this. Tell me, am I right or not ?

I launched the image, then after some time I recreated it. Creation began, but at that moment the connection with Azure was lost. Then, when the connection was restored, we tried to make a deployment that was not removed in the previous attempt (because there was no connection with Azure). As a result, we got such an error.

Does this theory make sense?
Thanks.

---
#### Сведения о документе

⚠ *Не вносите правки в этот раздел. Это необходимо для связывания страницы сайта docs.microsoft.com с вопросом на GitHub.*

* ID: a1b587f6-8bf4-fb64-5515-be223a17f783
* Version Independent ID: a756c758-417c-974d-1787-ad5e61edbd0b
* Content: [Устранение ошибок выделения ресурсов для виртуальных машин в Azure](https://docs.microsoft.com/ru-ru/azure/virtual-machines/troubleshooting/allocation-failure)
* Content Source: [articles/virtual-machines/troubleshooting/allocation-failure.md](https://github.com/MicrosoftDocs/azure-docs.ru-ru/blob/master/articles/virtual-machines/troubleshooting/allocation-failure.md)
* Service: **virtual-machines**
* GitHub Login: @JiangChen79
* Microsoft Alias: **cjiang**

**Comment by srvbpigh** [comment]
Hello, @ksereda
 
Thank you for your feedback.
 
We are actively reviewing your comments and will get back to you soon.


Kind regards,
Microsoft DOCS International Team

**Comment by CeciAc** [comment]
Issue moved to [MicrosoftDocs/azure-docs #43122](https://github.com/MicrosoftDocs/azure-docs/issues/43122) via [**ZenHub**](https://www.zenhub.com/)

**Comment by CeciAc** [comment]
Hello, @ksereda

Your contribution is much appreciated. Your feedback is related to the original documentation.
Hence, we are migrating this issue to the English repo. Please review the status of the issue here - https://github.com/MicrosoftDocs/azure-docs/issues/43122

We truly appreciate your contribution to our articles. 

Kind regards,
Microsoft DOCS International Team
