### ISSUE TITLE
Inaccurate data

### ISSUE THREAD

**Issue by AlexAlper** [MicrosoftDocs/azure-docs.ru-ru#60]
Щелкните Создать ресурс, выберите Вычисления, а затем щелкните Смотреть все в разделе Рекомендуемые приложения.
Щелкните JDK, а затем в области JDK выберите JDK 8.

Однако на Azure я не могу найти JDK, его там нет. И тогда я не знаю, как запустить Tomcat

---
#### Сведения о документе

⚠ *Не вносите правки в этот раздел. Это необходимо для связывания страницы сайта docs.microsoft.com с вопросом на GitHub.*

* ID: 6d30fbf5-0d12-9368-0cde-b16d6895e72a
* Version Independent ID: 4442b97f-731b-e9e6-e5f9-52b1d26a7707
* Content: [Запуск сервера приложений Java на классической виртуальной машине Azure](https://docs.microsoft.com/ru-ru/azure/virtual-machines/windows/classic/java-run-tomcat-app-server#feedback)
* Content Source: [articles/virtual-machines/windows/classic/java-run-tomcat-app-server.md](https://github.com/MicrosoftDocs/azure-docs.ru-ru/blob/live/articles/virtual-machines/windows/classic/java-run-tomcat-app-server.md)
* Service: **virtual-machines-windows**
* GitHub Login: @rmcmurray
* Microsoft Alias: **robmcm**

**Comment by CeciAc** [comment]
Issue moved to [MicrosoftDocs/azure-docs #10487](https://github.com/MicrosoftDocs/azure-docs/issues/10487) via [**ZenHub**](https://www.zenhub.com/)

**Comment by CeciAc** [comment]
Здравствуйте, @AlexAlper! 

Благодарим Вас за участие. Ваш отзыв связан с исходной документацией. 

Поэтому мы переносим Вашу заявку в репозиторий по английскому языку. Ее состояние можно просмотреть здесь: https://github.com/MicrosoftDocs/azure-docs/issues/10487. 

Мы очень ценим Ваш вклад в наши статьи.  

С наилучшими пожеланиями, 

Международная команда поддержки документации Майкрософт
