### ISSUE TITLE
wrong tags names

### ISSUE THREAD

**Issue by pashakot** [MicrosoftDocs/azure-docs.ru-ru#617]
Wrong tags names in Russian version of documentation 

---
#### Сведения о документе

⚠ *Не вносите правки в этот раздел. Это необходимо для связывания страницы сайта docs.microsoft.com с вопросом на GitHub.*

* ID: 08217244-82bb-13b5-46f7-454801d8f865
* Version Independent ID: 4a8b0a32-bf57-7544-c60d-6b7f250c4477
* Content: [Общие сведения о тегах служб Azure](https://docs.microsoft.com/ru-ru/azure/virtual-network/service-tags-overview#feedback)
* Content Source: [articles/virtual-network/service-tags-overview.md](https://github.com/MicrosoftDocs/azure-docs.ru-ru/blob/master/articles/virtual-network/service-tags-overview.md)
* Service: **virtual-network**
* GitHub Login: @jispar
* Microsoft Alias: **jispar**

**Comment by srvbpigh** [comment]
Hello, @pashakot
 
Thank you for your feedback.
 
We are actively reviewing your comments and will get back to you soon.


Kind regards,
Microsoft DOCS International Team

**Comment by ticianaciminari** [comment]
Hello @pashakot:

Thank you for your contribution. 

Contributions on translation problems against machine translated content are currently not accepted. 

We value your feedback and suggestions on human translated content, which is used to train the machine translation engines, so over time, your contributions will improve the quality of both human and machine translations. 

Human translated topics can be distinguished from machine translated topics by the ms.translationtype metadata value “HT” (versus “MT” for machine translated) in the header of each content file. 

Many thanks for your support. 

Microsoft DOCS Global Experience Team
