### ISSUE TITLE
Телеметрия метрик: модель данных Application Insights

### ISSUE THREAD

**Issue by astecenko** [MicrosoftDocs/azure-docs.ru-ru#62]
Опытным путем убедились что пользовательские метрики содержащие в своем названии сочетания символом "max" или "min" не отображаются в Application Insights. Т.е. например метрики my_custom_metric.max или my_custom_metric_min, и даже my_custom_metric_max2

Причем сервер принимает эти метрики без ошибок, они появляются в списке выбора метрик, но данные по этим метрикам не отображаются. Пробовал передавать подобные метрики и с помощью REST API, и с помощью Java SDK, результат один - метрики появляются в выборе, но данных нет. Стоит задать имя без сочетаний символов "max", "min" - данные отображаются.

Предполагаю что эти сочетания символов используются на сервере AI для какой-то служебной фильтрации или т.п. 

Хотелось бы чтобы документацию по метрикам дополнили списком зарезервированных слов (сочетаний символов) которые не рекомендуют использовать.

---
#### Сведения о документе

⚠ *Не вносите правки в этот раздел. Это необходимо для связывания страницы сайта docs.microsoft.com с вопросом на GitHub.*

* ID: 6039ead2-5836-d771-1f16-e71919bd6df3
* Version Independent ID: 1141f080-3f0c-8921-998d-876b09f1dfff
* Content: [Модель данных телеметрии Azure Application Insights — телеметрия метрик](https://docs.microsoft.com/ru-ru/azure/application-insights/application-insights-data-model-metric-telemetry)
* Content Source: [articles/application-insights/application-insights-data-model-metric-telemetry.md](https://github.com/MicrosoftDocs/azure-docs.ru-ru/blob/live/articles/application-insights/application-insights-data-model-metric-telemetry.md)
* Service: **application-insights**
* GitHub Login: @mrbullwinkle
* Microsoft Alias: **mbullwin; sergkanz**

**Comment by DavidPrio** [comment]
Здравствуйте, @astecenko! 
Благодарим Вас за участие. Ваш отзыв связан с исходной документацией. 
Поэтому мы переносим Вашу заявку в репозиторий по английскому языку. Ее состояние можно просмотреть здесь: https://github.com/MicrosoftDocs/azure-docs/issues/11507. 
Мы очень ценим Ваш вклад в наши статьи.  
С наилучшими пожеланиями, 

Международная команда поддержки документации Майкрософт
