### ISSUE TITLE
Опечатка

### ISSUE THREAD

**Issue by nikitos-mv** [MicrosoftDocs/azure-docs.ru-ru#638]
«Вопийте в свою учетную запись» вместо «Войдите в свою учетную запись»

---
#### Сведения о документе

⚠ *Не вносите правки в этот раздел. Это необходимо для связывания страницы сайта docs.microsoft.com с вопросом на GitHub.*

* ID: 276c38fe-aa72-6afa-23d8-14ff206c6f50
* Version Independent ID: 9ffe59dd-c667-4802-1da0-6917638804c5
* Content: [Общие проблемы с аутентификацией двух факторов учетной записи - Azure AD](https://docs.microsoft.com/ru-ru/azure/active-directory/user-help/multi-factor-authentication-end-user-troubleshoot#feedback)
* Content Source: [articles/active-directory/user-help/multi-factor-authentication-end-user-troubleshoot.md](https://github.com/MicrosoftDocs/azure-docs.ru-ru/blob/master/articles/active-directory/user-help/multi-factor-authentication-end-user-troubleshoot.md)
* Service: **active-directory**
* Sub-service: **user-help**
* GitHub Login: @curtand
* Microsoft Alias: **curtand**

**Comment by srvbpigh** [comment]
Hello, @nikitos-mv
 
Thank you for your feedback.
 
We are actively reviewing your comments and will get back to you soon.


Kind regards,
Microsoft DOCS International Team

**Comment by CeciAc** [comment]
Здравствуйте, @nikitos-mv 

Спасибо за Ваше предложение! 

Публикации о проблемах с содержимым, обработанным с помощью машинного перевода, сейчас не принимаются. 

Мы ценим ваши отзывы и предложения, касающиеся переведенного вручную содержимого. Мы используем их для обучения подсистем машинного перевода. Со временем это позволит улучшить качество как машинного, так и ручного перевода. 

Статьи, переведенные вручную, можно отличить от статей, обработанных с помощью машинного перевода, по значению метаданных ms.translationtype, которое равно "HT" (при использовании машинного перевода — "MT") в заголовке каждого файла с содержимым. 

Большое спасибо за поддержку! 

Microsoft DOCS Global Experience Team
