### ISSUE TITLE
Пример для .net core 2.1

### ISSUE THREAD

**Issue by DSpade-r** [MicrosoftDocs/azure-docs.ru-ru#64]
Кажется пример устарел, для новой версии Core 2.1 этот пример не работает.

---
#### Сведения о документе

⚠ *Не вносите правки в этот раздел. Это необходимо для связывания страницы сайта docs.microsoft.com с вопросом на GitHub.*

* ID: df26c5f6-63b9-d281-5724-c0731546b087
* Version Independent ID: 239bf87c-fcf0-b35e-744d-fecbb55501e4
* Content: [Руководство. Предоставление доступа к веб-API ASP.NET из веб-приложения с помощью Azure Active Directory B2C](https://docs.microsoft.com/ru-ru/azure/active-directory-b2c/active-directory-b2c-tutorials-web-api)
* Content Source: [articles/active-directory-b2c/active-directory-b2c-tutorials-web-api.md](https://github.com/MicrosoftDocs/azure-docs.ru-ru/blob/live/articles/active-directory-b2c/active-directory-b2c-tutorials-web-api.md)
* Service: **active-directory**
* GitHub Login: @davidmu1
* Microsoft Alias: **davidmu**

**Comment by CeciAc** [comment]
Здравствуйте, @DSpade-r! 
 Спасибо за отзыв. 
 Мы активно просматриваем комментарии и скоро ответим Вам. 
 С наилучшими пожеланиями, 
Международная команда поддержки документации Майкрософт

**Comment by CeciAc** [comment]
Issue moved to [MicrosoftDocs/azure-docs #15198](https://github.com/MicrosoftDocs/azure-docs/issues/15198) via [**ZenHub**](https://www.zenhub.com/)

**Comment by CeciAc** [comment]
Здравствуйте, @DSpade-r! 
Благодарим Вас за участие. Ваш отзыв связан с исходной документацией. 
Поэтому мы переносим Вашу заявку в репозиторий по английскому языку. Ее состояние можно просмотреть здесь: https://github.com/MicrosoftDocs/azure-docs/issues/15198. 
Мы очень ценим Ваш вклад в наши статьи.  
С наилучшими пожеланиями, 
Международная команда поддержки документации Майкрософт

**Comment by DSpade-r** [comment]
Здравствуйте @CeciAc. Спасибо за оперативный ответ.
