### ISSUE TITLE
Can I manage users from under another account (remotely, not through the portal)?

### ISSUE THREAD

**Issue by DSpade-r** [MicrosoftDocs/azure-docs.ru-ru#65]
Hello, tell me, please, is it possible to manage users from another account? For example, I have a manager who has certain rights in AD, he must create / delete (change) users, because users are not given such a direct right (in my situation, these are accounts for companies, not personal accounts)

---
#### Сведения о документе

⚠ *Не вносите правки в этот раздел. Это необходимо для связывания страницы сайта docs.microsoft.com с вопросом на GitHub.*

* ID: 849ddd08-b270-94d6-5551-ffa874636376
* Version Independent ID: 7d67048b-87c7-f2c9-d9b7-3820aee61822
* Content: [Добавление или удаление пользователей в Azure Active Directory](https://docs.microsoft.com/ru-ru/azure/active-directory/fundamentals/add-users-azure-active-directory)
* Content Source: [articles/active-directory/fundamentals/add-users-azure-active-directory.md](https://github.com/MicrosoftDocs/azure-docs.ru-ru/blob/live/articles/active-directory/fundamentals/add-users-azure-active-directory.md)
* Service: **active-directory**
* GitHub Login: @eross-msft
* Microsoft Alias: **lizross**

**Comment by LisandroSu** [comment]
Hello, @DSpade-r ,

Your contribution is much appreciated. Our team can only answer feedback related to the documentation.
Please kindly log your product feedback by using the button "Give Product Feedback" at the bottom of the DOCS page.

If you have any feedback related to the documentation, please feel free to log it through this channel.
We truly appreciate your contribution to our articles. 
	
Kind regards,
Microsoft DOCS International Team
