### ISSUE TITLE
MBps

### ISSUE THREAD

**Issue by stenastena** [MicrosoftDocs/azure-docs.ru-ru#67]
При  переводе для ряда параметров, связанных с пропускной способностью дисков перепутаны МБайт/с  и Мбит/с. В оригинальном англоязычном варианте везде указаны MBps, что означает МБайт за секунду , однако при переводе они превратились в МБит/с , что неправильно. Должны переводиться как  МБайт/с. 

---
#### Сведения о документе

⚠ *Не вносите правки в этот раздел. Это необходимо для связывания страницы сайта docs.microsoft.com с вопросом на GitHub.*

* ID: 9bb1d37c-6337-0906-42ff-b5dbc6afdc8b
* Version Independent ID: 72a96e16-1d2d-4c01-45be-3caf82470592
* Content: [Размеры виртуальных машин Windows в Azure общего назначения](https://docs.microsoft.com/ru-ru/azure/virtual-machines/windows/sizes-general)
* Content Source: [articles/virtual-machines/windows/sizes-general.md](https://github.com/MicrosoftDocs/azure-docs.ru-ru/blob/live/articles/virtual-machines/windows/sizes-general.md)
* Service: **virtual-machines-windows**
* GitHub Login: @jonbeck7
* Microsoft Alias: **jonbeck**

**Comment by LisandroSu** [comment]
Здравствуйте, @stenastena ! 

 Спасибо за отзыв. 

 Мы активно просматриваем комментарии и скоро ответим Вам. 

 С наилучшими пожеланиями, 
Международная команда поддержки документации Майкрософт

**Comment by LisandroSu** [comment]
Здравствуйте, @stenastena !  

Спасибо за отзыв. 

Наши лингвисты рассмотрели Ваши предложения и приняли их. Мы внедрили Ваши правки в обновленные статьи на сайте документации, опубликованные на следующих страницах: [Размеры виртуальных машин Windows в Azure общего назначения](https://docs.microsoft.com/ru-ru/azure/virtual-machines/windows/sizes-general).  

Мы очень ценим Ваш вклад в наши статьи и будем рады получить другие полезные отзывы. 
С наилучшими пожеланиями, 

Международная команда поддержки документации Майкрософт
