### ISSUE TITLE
Кто такой denisenkom?

### ISSUE THREAD

**Issue by gromas** [MicrosoftDocs/azure-docs.ru-ru#75]
И чем это может грозить в дальнейшем. Предлагаю задуматься всем. Спасибо.

---
#### Сведения о документе

⚠ *Не вносите правки в этот раздел. Это необходимо для связывания страницы сайта docs.microsoft.com с вопросом на GitHub.*

* ID: 44fb6283-7b17-7ae4-5ad4-bf5bb5702e7f
* Version Independent ID: f19e7d27-dce2-c34b-a666-a8ed2862c087
* Content: [Использование Go для создания запросов к базе данных SQL Azure](https://docs.microsoft.com/ru-ru/azure/sql-database/sql-database-connect-query-go)
* Content Source: [articles/sql-database/sql-database-connect-query-go.md](https://github.com/MicrosoftDocs/azure-docs.ru-ru/blob/live/articles/sql-database/sql-database-connect-query-go.md)
* Service: **sql-database**
* GitHub Login: @David-Engel
* Microsoft Alias: **v-daveng**

**Comment by CeciAc** [comment]
Issue moved to [MicrosoftDocs/azure-docs #19703](https://github.com/MicrosoftDocs/azure-docs/issues/19703) via [**ZenHub**](https://www.zenhub.com/)

**Comment by CeciAc** [comment]
Здравствуйте, @gromas 
Благодарим Вас за участие. Ваш отзыв связан с исходной документацией. 
Поэтому мы переносим Вашу заявку в репозиторий по английскому языку. Ее состояние можно просмотреть здесь: https://github.com/MicrosoftDocs/azure-docs/issues/19703. 
Мы очень ценим Ваш вклад в наши статьи.  
С наилучшими пожеланиями, 
Международная команда поддержки документации Майкрософт
