### ISSUE TITLE
X

### ISSUE THREAD

**Issue by pilot-kc** [MicrosoftDocs/azure-docs.ru-ru#93]
Yyyy

---
#### Сведения о документе

⚠ *Не вносите правки в этот раздел. Это необходимо для связывания страницы сайта docs.microsoft.com с вопросом на GitHub.*

* ID: 3b0550e7-e5e2-69d1-03a8-f678c3fe0eee
* Version Independent ID: 877db3da-b145-7bfd-3544-30a420de7d13
* Content: [Приступая к работе с приложением Microsoft Authenticator: Azure Active Directory](https://docs.microsoft.com/ru-ru/azure/active-directory/user-help/microsoft-authenticator-app-how-to#add-accounts-to-the-app)
* Content Source: [articles/active-directory/user-help/microsoft-authenticator-app-how-to.md](https://github.com/MicrosoftDocs/azure-docs.ru-ru/blob/live/articles/active-directory/user-help/microsoft-authenticator-app-how-to.md)
* Service: **active-directory**
* GitHub Login: @eross-msft
* Microsoft Alias: **lizross**

**Comment by CeciAc** [comment]
The feedback is empty. I'm closing this issue.
